/**
 * FAhubX .env Generator
 *
 * Generates the backend .env file from installer wizard parameters.
 * Auto-generates cryptographically strong secrets for JWT, encryption, etc.
 *
 * Usage: node generate-env.js --mode <cloud|local> --app-port <port>
 *        --pg-port <port> --redis-port <port> --install-dir <path>
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

function parseArgs() {
  const args = process.argv.slice(2);
  const params = {};
  for (let i = 0; i < args.length; i += 2) {
    const key = args[i].replace(/^--/, '');
    params[key] = args[i + 1];
  }
  return params;
}

function generateHex(length) {
  return crypto.randomBytes(length).toString('hex');
}

function generatePassword(length = 24) {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789!@#$%';
  const bytes = crypto.randomBytes(length);
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars[bytes[i] % chars.length];
  }
  return result;
}

function main() {
  const params = parseArgs();

  const deployMode = params['mode'] || 'local';
  const appPort = params['app-port'] || '9600';
  const pgPort = params['pg-port'] || '5433';
  const redisPort = params['redis-port'] || '6380';
  const installDir = params['install-dir'] || process.cwd();

  // 如果 .env 已存在，读取已有的密钥和密码（避免每次重装把密码加密key 换掉 → 导致已存账号的密码解不出来）
  const envPath = path.join(installDir, 'backend', '.env');
  const existing = {};
  if (fs.existsSync(envPath)) {
    const content = fs.readFileSync(envPath, 'utf-8');
    for (const line of content.split(/\r?\n/)) {
      const m = line.match(/^([A-Z_]+)=(.*)$/);
      if (m) existing[m[1]] = m[2];
    }
    console.log(`[INFO] 检测到已有 .env，保留原有密钥避免破坏已加密数据`);
  }

  // Generate strong secrets (只在首次生成时创建新值)
  const jwtSecret = existing.JWT_SECRET || generateHex(32);           // 64 hex chars
  const jwtRefreshSecret = existing.JWT_REFRESH_SECRET || generateHex(32);    // 64 hex chars
  const encryptionKey = existing.ENCRYPTION_KEY || generateHex(16);   // 32 hex chars
  const sessionSecret = existing.SESSION_SECRET || generateHex(24);   // 48 hex chars
  const dbPassword = existing.DB_PASSWORD || generatePassword(20);    // random (for main.ts guard)

  const envContent = `# ============================================================
# FAhubX Configuration - Auto-generated by installer
# Generated: ${new Date().toISOString()}
# ============================================================

# --- Application ---
NODE_ENV=production
DEPLOY_MODE=${deployMode}
APP_NAME=FAhubX
PORT=${appPort}
HOST=127.0.0.1
API_PREFIX=api

# --- Database (PostgreSQL) ---
DB_HOST=127.0.0.1
DB_PORT=${pgPort}
DB_NAME=fbautobot
DB_USER=postgres
DB_PASSWORD=${dbPassword}
DB_SYNC=false
DB_LOGGING=false
DB_SSL=false

# --- Cache (Redis) ---
REDIS_HOST=127.0.0.1
REDIS_PORT=${redisPort}
REDIS_PASSWORD=
REDIS_DB=0

# --- Authentication ---
JWT_SECRET=${jwtSecret}
JWT_EXPIRES_IN=7d
JWT_REFRESH_SECRET=${jwtRefreshSecret}
JWT_REFRESH_EXPIRES_IN=30d

# --- Encryption ---
ENCRYPTION_KEY=${encryptionKey}
SESSION_SECRET=${sessionSecret}

# --- CORS ---
CORS_ORIGIN=http://localhost:${appPort}
CORS_CREDENTIALS=true

# --- Features ---
SWAGGER_ENABLED=false
COMPRESSION_ENABLED=true
SERVE_STATIC=true
FRONTEND_DIST_PATH=../frontend/dist

# --- 本地数据目录（绝对路径） ---
BROWSER_DATA_DIR=${installDir.replace(/\\/g, '/')}/data/browsers
SCREENSHOT_DIR=${installDir.replace(/\\/g, '/')}/data/screenshots
DOWNLOADS_DIR=${installDir.replace(/\\/g, '/')}/data/downloads

# --- Chromium 路径（已打包进安装包，无需租户下载） ---
PUPPETEER_CACHE_DIR=${installDir.replace(/\\/g, '/')}/backend/puppeteer-cache
PUPPETEER_SKIP_DOWNLOAD=true

# --- Security ---
CONTENT_SECURITY_POLICY=false
HSTS_ENABLED=false

# --- License (Local mode) ---
LICENSE_SERVER_URL=https://license.starbright-solutions.com
LICENSE_KEY=

# --- Rate Limiting ---
RATE_LIMIT_WINDOW=900000
RATE_LIMIT_MAX=200

# --- Task Configuration ---
TASK_RETRY_MAX_ATTEMPTS=3
TASK_RETRY_DELAY=300000
TASK_TIMEOUT=1800000
`;

  // Write .env to backend directory (envPath 上面已声明)
  fs.mkdirSync(path.dirname(envPath), { recursive: true });
  fs.writeFileSync(envPath, envContent, 'utf-8');

  console.log(`[OK] .env generated: ${envPath}`);
  console.log(`  Deploy Mode: ${deployMode}`);
  console.log(`  App Port: ${appPort}`);
  console.log(`  PostgreSQL Port: ${pgPort}`);
  console.log(`  Redis Port: ${redisPort}`);
}

main();
